### ISSUE TITLE
Typo in CORE-Agent prompts

### ISSUE THREAD

**Issue by tbayer** [siegelz/core-bench#37]
I assume "figuclearres" should read "figures" in this line that appears in e.g. [coreagent_hard_gpt4o.sh](https://github.com/siegelz/core-bench/blob/b1df2fb0ba0d0b2f16de88b36c4b9f13aded177e/agents/AutoGPT-CORE/coreagent_hard_gpt4o.sh#L65) and [the other agent scripts](https://github.com/search?q=repo%3Asiegelz%2Fcore-bench%20figuclearres&type=code) under agents/AutoGPT-CORE:

`--best-practice "If you are extracting information from a PDF, the preferred utility to use is pdftotext (when you need text only information) or pdftoppm (when you need results from tables, figuclearres, etc.)." \`

**Comment by siegelz** [comment]
Thank you, fixed!
